"""Per-worker Kaggle push folders: notebook + kernel-metadata.json.

One folder per worker account, rebuilt before every dispatch:

* ``davidnet_q1_pipeline.ipynb`` - generated by kaggle/build_notebook.py with this
  worker's ``session.worker_name`` (the HF claim/lease layer keys on it)
* ``kernel-metadata.json``        - private, GPU on, internet on, the seven corpus
  datasets attached, plus this worker's private HF-token dataset

Why the token dataset: ``kaggle kernels push`` detaches notebook Secrets, but input
datasets stay attached. ``ensure_secret_dataset()`` ships ``hf_token.txt`` in a private
dataset owned by the worker's own account; ``src/pipeline/hub.py::resolve_hf_token``
reads it as the fallback after Secrets and the ``HF_TOKEN`` env var.
"""
from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

from .config import REPO_ROOT, SETTINGS, Settings, WorkerCredential, hf_token
from .kaggle_client import KaggleClient, KaggleError

_NOTEBOOK_NAME = "davidnet_q1_pipeline.ipynb"


def _load_build_notebook():
    """Import kaggle/build_notebook.py by path (the repo's kaggle/ is not a package
    and would otherwise be shadowed by the installed ``kaggle`` CLI package)."""
    path = REPO_ROOT / "kaggle" / "build_notebook.py"
    spec = importlib.util.spec_from_file_location("davidnet_build_notebook", path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = mod
    spec.loader.exec_module(mod)
    return mod


def kernel_ref(worker: WorkerCredential, settings: Settings = SETTINGS) -> str:
    return f"{worker.username}/{settings.kernel_slug}"


def secret_dataset_ref(worker: WorkerCredential, settings: Settings = SETTINGS) -> str:
    return f"{worker.username}/{settings.secret_dataset_slug}"


def dataset_sources(worker: WorkerCredential, settings: Settings = SETTINGS) -> list[str]:
    return list(settings.data_datasets) + [secret_dataset_ref(worker, settings)]


def build_push_folder(worker: WorkerCredential, *, settings: Settings = SETTINGS,
                      mode: str | None = None, revision: str | None = None,
                      out: Path | str | None = None) -> Path:
    """Write the complete push folder for one worker and return its path."""
    out_dir = Path(out) if out else settings.work_dir / "push" / worker.name
    out_dir.mkdir(parents=True, exist_ok=True)

    build = _load_build_notebook()
    build.build_notebook(
        worker=worker.name,                       # session.worker_name, unique per account
        mode=mode or settings.mode,
        revision=revision or settings.code_revision,
        hf_repo=settings.hf_repo,
        out=out_dir / _NOTEBOOK_NAME,
    )

    metadata = {
        "id": kernel_ref(worker, settings),
        # Kaggle derives the slug from the title for new kernels: keep them in sync.
        "title": settings.kernel_slug.replace("-", " "),
        "code_file": _NOTEBOOK_NAME,
        "language": "python",
        "kernel_type": "notebook",
        "is_private": "true",
        "enable_gpu": "true",
        "enable_internet": "true",                # HF uploads, git clone, model downloads
        "machine_shape": settings.accelerator,
        "dataset_sources": dataset_sources(worker, settings),
        "competition_sources": [],
        "kernel_sources": [],
        "model_sources": [],
    }
    (out_dir / "kernel-metadata.json").write_text(
        json.dumps(metadata, indent=2) + "\n", encoding="utf-8")
    return out_dir


def build_secret_folder(worker: WorkerCredential, token: str | None = None, *,
                        settings: Settings = SETTINGS, out: Path | str | None = None) -> Path:
    """Folder holding hf_token.txt + dataset-metadata.json (never printed, gitignored)."""
    out_dir = Path(out) if out else settings.work_dir / "secret" / worker.name
    out_dir.mkdir(parents=True, exist_ok=True)
    token = token or hf_token()
    if not token:
        raise KaggleError(f"no HF token in .env - cannot build secret dataset for {worker.name}")
    tok_file = out_dir / "hf_token.txt"
    tok_file.write_text(token.strip() + "\n", encoding="utf-8")
    try:
        tok_file.chmod(0o600)                     # best effort (no-op on Windows)
    except OSError:
        pass
    metadata = {
        # title: 6-50 chars (Kaggle rule); id: username/slug, both per-worker
        "title": f"DAVIDNET HF token {worker.name}"[:50],
        "id": secret_dataset_ref(worker, settings),
        "description": "Private: HF write token consumed by the DAVID-Net Kaggle "
                       "pipeline notebook (hf_token.txt).",
        "licenses": [{"name": "CC0-1.0"}],
    }
    (out_dir / "dataset-metadata.json").write_text(
        json.dumps(metadata, indent=2) + "\n", encoding="utf-8")
    return out_dir


def ensure_secret_dataset(client: KaggleClient, token: str | None = None, *,
                          settings: Settings = SETTINGS) -> str:
    """Create (or version) the worker's private HF-token dataset; return its ref."""
    folder = build_secret_folder(client.worker, token=token, settings=settings)
    try:
        client.datasets_create(str(folder))
    except KaggleError:
        # already exists (or a concurrent first run) -> new version with same bytes
        client.datasets_update(str(folder), message=f"refresh {settings.secret_dataset_slug}")
    return secret_dataset_ref(client.worker, settings)
